# Generated by Django 3.2.8 on 2021-10-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_name',
            new_name='product_name',
        ),
    ]
